services:
  mindsdb:
    image: mindsdb/mindsdb:latest
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - mindsdb_data:/root/mdb_storage
    env_file:
      - .env

volumes:
  mindsdb_data:
